# -*- encoding: utf-8 -*-
from personas.models import *
from territorios.models import *
Grado.objects.create(numero=1)
Grado.objects.create(numero=2)
Grado.objects.create(numero=3)
Grado.objects.create(numero=4)
Grado.objects.create(numero=5)
Grado.objects.create(numero=6)
Grado.objects.create(numero=7)
Grado.objects.create(numero=8)
Grado.objects.create(numero=9)
Grado.objects.create(numero=10)
Grado.objects.create(numero=11)
Grado.objects.create(numero=12)
Grado.objects.create(numero=13)
Grado.objects.create(numero=14)
Grado.objects.create(numero=15)
Grado.objects.create(numero=16)
Grado.objects.create(numero=17)
Grado.objects.create(numero=18)
Grado.objects.create(numero=19)
Grado.objects.create(numero=20)
Grado.objects.create(numero=21)
Grado.objects.create(numero=22)
Grado.objects.create(numero=23)
Estamento.objects.create(nombre='Profesional')
Estamento.objects.create(nombre='Fiscalizador')
Estamento.objects.create(nombre='Tecnico')
Estamento.objects.create(nombre='Administrativo')
Estamento.objects.create(nombre='Auxiliar')
Escalafon.objects.create(nombre="Planta")
Escalafon.objects.create(nombre="Contrata")
Escalafon.objects.create(nombre="Honorarios")
Unidad.objects.create(nombre="Administracion")
Unidad.objects.create(nombre="Fiscalizacion")
Unidad.objects.create(nombre="Juridica")
Unidad.objects.create(nombre="Denuncia")
Unidad.objects.create(nombre="Gabinete")

Region.objects.create(numero='XV',nombre='Region de Arica y Parinacota')
Provincia.objects.create(nombre="Arica",region=Region.objects.get(pk=1))
Provincia.objects.create(nombre="Parinacota",region=Region.objects.get(pk=1))

Region.objects.create(numero='I',nombre='Region de Tarapaca')
Provincia.objects.create(nombre="Iquique",region=Region.objects.get(pk=2))
Provincia.objects.create(nombre="Tamarugal",region=Region.objects.get(pk=2))

Region.objects.create(numero='II',nombre='Region de Antofagasta')
Provincia.objects.create(nombre="Antofagasta",region=Region.objects.get(pk=3))
Provincia.objects.create(nombre="El Loa",region=Region.objects.get(pk=3))
Provincia.objects.create(nombre="Tocopilla",region=Region.objects.get(pk=3))

Region.objects.create(numero='III',nombre='Region de Atacama')
Provincia.objects.create(nombre="Copiapo",region=Region.objects.get(pk=4))
Provincia.objects.create(nombre="Chanaral",region=Region.objects.get(pk=4))
Provincia.objects.create(nombre="El Huasco",region=Region.objects.get(pk=4))

Region.objects.create(numero='IV',nombre='Region de Coquimbo')
Provincia.objects.create(nombre="Elqui",region=Region.objects.get(pk=5))
Provincia.objects.create(nombre="Choapa",region=Region.objects.get(pk=5))
Provincia.objects.create(nombre="Limari",region=Region.objects.get(pk=5))

Region.objects.create(numero='V',nombre='Region de Valparaiso')
Provincia.objects.create(nombre="Valparaiso",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="Isla de Pascua",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="Los Andes",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="Petorca",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="Quillota",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="San Antonio",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="San Felipe de Aconcagua",region=Region.objects.get(pk=6))
Provincia.objects.create(nombre="Marga Marga",region=Region.objects.get(pk=6))

Region.objects.create(numero='RM',nombre='Region Metropolitana de Santiago')
Provincia.objects.create(nombre="Santiago",region=Region.objects.get(pk=7))
Provincia.objects.create(nombre="Cordillera",region=Region.objects.get(pk=7))
Provincia.objects.create(nombre="Chacabuco",region=Region.objects.get(pk=7))
Provincia.objects.create(nombre="Maipo",region=Region.objects.get(pk=7))
Provincia.objects.create(nombre="Melipilla",region=Region.objects.get(pk=7))
Provincia.objects.create(nombre="Talagante",region=Region.objects.get(pk=7))

Region.objects.create(numero='VI',nombre="Region del Libertador Bernado O'Higgins")
Provincia.objects.create(nombre="Cachapoal",region=Region.objects.get(pk=8))
Provincia.objects.create(nombre="Cardenal Caro",region=Region.objects.get(pk=8))
Provincia.objects.create(nombre="Colchagua",region=Region.objects.get(pk=8))

Region.objects.create(numero='VII',nombre='Region del Maule')
Provincia.objects.create(nombre="Talca",region=Region.objects.get(pk=9))
Provincia.objects.create(nombre="Cauquenes",region=Region.objects.get(pk=9))
Provincia.objects.create(nombre="Curico",region=Region.objects.get(pk=9))
Provincia.objects.create(nombre="Linares",region=Region.objects.get(pk=9))

Region.objects.create(numero='VIII',nombre='Region del Bio Bio')
Provincia.objects.create(nombre="Concepcion",region=Region.objects.get(pk=10))
Provincia.objects.create(nombre="Arauco",region=Region.objects.get(pk=10))
Provincia.objects.create(nombre="BioBio",region=Region.objects.get(pk=10))
Provincia.objects.create(nombre="Nuble",region=Region.objects.get(pk=10))

Region.objects.create(numero='IX',nombre='Region de La Araucania')
Provincia.objects.create(nombre="Cautin",region=Region.objects.get(pk=11))
Provincia.objects.create(nombre="Malleco",region=Region.objects.get(pk=11))

Region.objects.create(numero='XIV',nombre='Region de Los Rios')
Provincia.objects.create(nombre="Valdivia",region=Region.objects.get(pk=12))
Provincia.objects.create(nombre="Ranco",region=Region.objects.get(pk=12))

Region.objects.create(numero='X',nombre='Region de Los Lagos')
Provincia.objects.create(nombre="Llanquihue",region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Puerto Montt",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Calbuco",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Cochamo",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Fresia",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Frutilla",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Los Muermos",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Llanquihue",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Maullin",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Puerto Varas",provincia=Provincia.objects.get(pk=43),region=Region.objects.get(pk=13))

Provincia.objects.create(nombre="Osorno",region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Osorno",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Puerto Octay",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Purranque",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Puyehue",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Rio Negro",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="San Juan de la Costa",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="San Pablo",provincia=Provincia.objects.get(pk=44),region=Region.objects.get(pk=13))

Provincia.objects.create(nombre="Chiloe",region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Castro",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Ancud",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Chonchi",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Curaco de Velez",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Dalcahue",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Puqueldon",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Queilen",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Quellon",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Quemchi",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Quinchao",provincia=Provincia.objects.get(pk=45),region=Region.objects.get(pk=13))

Provincia.objects.create(nombre="Palena",region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Chaiten",provincia=Provincia.objects.get(pk=46),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Futaleufu",provincia=Provincia.objects.get(pk=46),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Hualaihue",provincia=Provincia.objects.get(pk=46),region=Region.objects.get(pk=13))
Comuna.objects.create(nombre="Palena",provincia=Provincia.objects.get(pk=46),region=Region.objects.get(pk=13))

Region.objects.create(numero='XI',nombre="Region de Aysen del General Carlos Ibanez del Campo")
Provincia.objects.create(nombre="Coyhaique",region=Region.objects.get(pk=14))
Provincia.objects.create(nombre="Aysen",region=Region.objects.get(pk=14))
Provincia.objects.create(nombre="Capitan Prat",region=Region.objects.get(pk=14))
Provincia.objects.create(nombre="General Carrera",region=Region.objects.get(pk=14))

Region.objects.create(numero='XII',nombre='Region de Magallanes y La Antartica Chilena')
Provincia.objects.create(nombre="Magallanes",region=Region.objects.get(pk=15))
Provincia.objects.create(nombre="Antartica Chilena",region=Region.objects.get(pk=15))
Provincia.objects.create(nombre="Tierra del Fuego",region=Region.objects.get(pk=15))
Provincia.objects.create(nombre="Ultima Esperanza",region=Region.objects.get(pk=15))
