# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import territorios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['provincia'],
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['region'],
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3, verbose_name='Numero')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=territorios.models.Region, to='territorios.Region'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=territorios.models.Provincia, to='territorios.Provincia'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=territorios.models.Region, to='territorios.Region'),
        ),
    ]
