# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaAerea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Linea Aerea')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Lineas Aereas',
            },
        ),
        migrations.CreateModel(
            name='LineaBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Linea Bus')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Linea de Buses',
            },
        ),
    ]
